{
    "name": "SMQ - Pont Qualité (Non-conformités & Actions)",
    "summary": "Intègre les moteurs OCA Non-conformité / Action au SMQ (processus, documents, tableau de bord)",
    "version": "17.0.1.0.0",
    "category": "Quality",
    "author": "Medianet",
    "license": "AGPL-3",
    "application": False,
    "depends": [
        "smq_quality",
        "smq_document",
        "mgmtsystem_nonconformity",
        "mgmtsystem_action",
        "mgmtsystem_action_efficacy",
        "mgmtsystem_audit",
        "mgmtsystem_action_template",
        "mgmtsystem_nonconformity_type",
        "mgmtsystem_nonconformity_hr",
        "mgmtsystem_review",
        "mgmtsystem_review_survey",
        "hr_skills",
        "smq_risk",
        "smq_complaint",
        "smq_training",
        "smq_supplier",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/mgmtsystem_sequence_data.xml",
        "data/mgmtsystem_nonconformity_stage_data.xml",
        "data/mgmtsystem_nonconformity_severity_data.xml",
        "data/mgmtsystem_nonconformity_origin_data.xml",
        "data/mgmtsystem_security_data.xml",
        "views/mgmtsystem_nonconformity_views.xml",
        "views/mgmtsystem_action_views.xml",
        "views/mgmtsystem_audit_views.xml",
        "views/mgmtsystem_review_views.xml",
        "views/hr_employee_skill_views.xml",
        "views/smq_process_views.xml",
        "views/smq_document_views.xml",
        "views/smq_quality_bridge_menus.xml",
        "data/smq_dashboard_kpi_data.xml",
        "report/mgmtsystem_review_report.xml",
        "demo/mgmtsystem_nonconformity_demo.xml",
        "demo/mgmtsystem_audit_demo.xml",
        "demo/mgmtsystem_review_demo.xml",
    ],
}
