{
    "name": "SMQ - Quality Core",
    "summary": "Cœur applicatif du SMQ : processus qualité, sécurité commune, menu racine",
    "version": "17.0.1.0.0",
    "category": "Quality",
    "author": "Medianet",
    "license": "AGPL-3",
    "application": True,
    "depends": ["mail"],
    "data": [
        "security/smq_quality_security.xml",
        "security/ir.model.access.csv",
        "data/smq_process_category_data.xml",
        "views/smq_process_views.xml",
        "data/smq_dashboard_tile_data.xml",
        "views/smq_dashboard_views.xml",
        "views/smq_quality_menus.xml",
        "demo/smq_process_demo.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "smq_quality/static/src/scss/smq_tokens.scss",
            "smq_quality/static/src/scss/smq_dashboard.scss",
            "smq_quality/static/src/scss/smq_sidebar.scss",
            "smq_quality/static/src/js/smq_coming_soon_dialog.js",
            "smq_quality/static/src/js/smq_dashboard.js",
            "smq_quality/static/src/js/smq_sidebar_config.js",
            "smq_quality/static/src/js/smq_sidebar.js",
            "smq_quality/static/src/js/smq_webclient_patch.js",
            "smq_quality/static/src/xml/smq_dashboard.xml",
            "smq_quality/static/src/xml/smq_sidebar.xml",
            "smq_quality/static/src/xml/smq_webclient_patch.xml",
        ],
    },
}
